import { randomUUID } from "node:crypto";

import { ACTIVE_UPLOAD_STATUSES, DEFAULT_PAGE_SIZE } from "@openspace/shared";

// Convert a raw SQLite upload row into a cleaner
// JavaScript object using camelCase property names.
function mapUpload(row) {
  // If no database row was found, return null.
  if (!row) return null;

  return {
    // Local upload ID generated by this application.
    id: row.id,

    // IDs returned by the OpenSpace API.
    captureId: row.capture_id,
    openSpaceUploadId: row.openspace_upload_id,

    // Project / floor information.
    siteId: row.site_id,
    projectName: row.project_name,
    sheetId: row.sheet_id,
    floorName: row.floor_name,

    // Capture and device information.
    captureName: row.capture_name,
    deviceId: row.device_id,
    fileName: row.device_filename,
    fileSize: row.file_size,
    capturedAt: row.captured_at,

    // Starting position / capture metadata.
    startMicro: row.start_micro,

    // Convert three database coordinate columns
    // into a single JavaScript array: [x, y, z].
    startPosition: [row.start_x, row.start_y, row.start_z],

    // Upload state and progress information.
    status: row.status,
    uploadProgress: row.upload_progress,
    bytesSent: row.bytes_sent,
    retryCount: row.retry_count,
    errorMessage: row.error_message,

    // OpenSpace viewer link after upload/submission.
    viewerUrl: row.viewer_url,

    // SQLite commonly stores booleans as 0 or 1.
    // Convert it into a real JavaScript boolean.
    localFileDeleted: Boolean(row.local_file_deleted),

    // Important timestamps for the upload lifecycle.
    uploadStartedAt: row.upload_started_at,
    submittedAt: row.submitted_at,
    processingCompletedAt: row.processing_completed_at,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// Create the upload repository.
// This repository handles all database operations related to uploads.
export function createUploadRepository(database) {
  // Find a single upload using its local upload ID.
  //
  // By default, the local file path is hidden.
  // Set includeLocalPath to true only when the application
  // needs access to the actual local INSV file.
  function findById(id, { includeLocalPath = false } = {}) {
    const row = database.prepare("SELECT * FROM uploads WHERE id = ?").get(id);

    // Upload does not exist.
    if (!row) return null;

    const upload = mapUpload(row);

    // Only expose the local path when specifically requested.
    if (includeLocalPath) {
      upload.localFilePath = row.local_file_path;
    }

    return upload;
  }

  // Find an upload and throw an error if it does not exist.
  //
  // This avoids repeating the same validation code
  // in every update function.
  function requireUpload(id, options) {
    const upload = findById(id, options);

    if (!upload) {
      throw new Error("Upload was not found.");
    }

    return upload;
  }

  // Create a new upload record in the database.
  function create(input) {
    // Current timestamp.
    const now = new Date().toISOString();

    // Generate a unique local ID for this upload.
    const id = randomUUID();

    database
      .prepare(
        `
        INSERT INTO uploads (
          id,
          site_id,
          project_name,
          sheet_id,
          floor_name,
          capture_name,
          device_id,
          device_filename,
          local_file_path,
          file_size,
          captured_at,
          start_micro,
          start_x,
          start_y,
          start_z,
          status,
          created_at,
          updated_at
        )
        VALUES (
          @id,
          @siteId,
          @projectName,
          @sheetId,
          @floorName,
          @captureName,
          @deviceId,
          @fileName,
          @localFilePath,
          @fileSize,
          @capturedAt,
          @startMicro,
          @startX,
          @startY,
          @startZ,

          -- Every new upload starts in the "staged" state.
          'staged',

          @now,
          @now
        )
      `,
      )
      .run({
        id,
        ...input,
        now,
      });

    // Return the newly created upload.
    return findById(id);
  }

  // Return uploads using optional filters and pagination.
  //
  // Supported filters:
  // - search
  // - status
  // - siteId
  // - from
  // - to
  // - page
  // - pageSize
  function list(filters = {}) {
    // Store dynamically generated WHERE conditions.
    const conditions = [];

    // Store SQL parameters separately from SQL text.
    const parameters = {};

    // Search across several text fields.
    if (filters.search) {
      conditions.push(`
        (
          capture_name LIKE @search
          OR device_filename LIKE @search
          OR project_name LIKE @search
          OR floor_name LIKE @search
        )
      `);

      // Example:
      // search = "PSB"
      // becomes "%PSB%"
      parameters.search = `%${filters.search}%`;
    }

    // Filter by upload status.
    if (filters.status) {
      conditions.push("status = @status");

      parameters.status = filters.status;
    }

    // Filter uploads belonging to a specific project/site.
    if (filters.siteId) {
      conditions.push("site_id = @siteId");

      parameters.siteId = filters.siteId;
    }

    // Only include captures on or after this date/time.
    if (filters.from) {
      conditions.push("captured_at >= @from");

      parameters.from = filters.from;
    }

    // Only include captures on or before this date/time.
    if (filters.to) {
      conditions.push("captured_at <= @to");

      parameters.to = filters.to;
    }

    // Build the WHERE clause only if filters exist.
    //
    // Example:
    //
    // WHERE status = @status
    // AND site_id = @siteId
    const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";

    // Determine page size.
    //
    // Minimum: 1
    // Maximum: 100
    // Default: DEFAULT_PAGE_SIZE
    const pageSize = Math.min(
      Math.max(Number(filters.pageSize) || DEFAULT_PAGE_SIZE, 1),
      100,
    );

    // Make sure page number is at least 1.
    const page = Math.max(Number(filters.page) || 1, 1);

    // SQL LIMIT controls how many rows are returned.
    parameters.limit = pageSize;

    // SQL OFFSET controls where the page starts.
    //
    // Page 1 -> offset 0
    // Page 2 -> offset pageSize
    // Page 3 -> offset pageSize * 2
    parameters.offset = (page - 1) * pageSize;

    // Fetch the current page of uploads.
    // Newest uploads appear first.
    const rows = database
      .prepare(
        `
        SELECT *
        FROM uploads
        ${where}
        ORDER BY created_at DESC
        LIMIT @limit
        OFFSET @offset
      `,
      )
      .all(parameters);

    // Count the total number of uploads matching
    // the filters, ignoring pagination.
    const total = database
      .prepare(
        `
        SELECT COUNT(*) AS total
        FROM uploads
        ${where}
      `,
      )
      .get(parameters).total;

    return {
      // Convert database rows into application objects.
      items: rows.map(mapUpload),

      page,
      pageSize,
      total,
    };
  }

  // Return the most recently created uploads.
  //
  // Default: 5
  // Minimum: 1
  // Maximum: 20
  function getRecent(limit = 5) {
    const safeLimit = Math.min(Math.max(Number(limit) || 5, 1), 20);

    return database
      .prepare(
        `
        SELECT *
        FROM uploads
        ORDER BY created_at DESC
        LIMIT ?
      `,
      )
      .all(safeLimit)
      .map(mapUpload);
  }

  // Return summary statistics used by a dashboard.
  //
  // Example result:
  // {
  //   totalUploads: 20,
  //   inProgress: 4,
  //   completed: 13,
  //   failed: 3
  // }
  function getDashboardSummary() {
    // Suppose:
    //
    // ACTIVE_UPLOAD_STATUSES =
    // ["staged", "uploading", "submitted", "processing"]
    //
    // This creates:
    //
    // "?,?,?,?"
    //
    // so it can be used inside SQL:
    //
    // status IN (?, ?, ?, ?)
    const activePlaceholders = ACTIVE_UPLOAD_STATUSES.map(() => "?").join(",");

    const row = database
      .prepare(
        `
        SELECT
          COUNT(*) AS total_uploads,

          -- Count uploads that are still active/in progress.
          SUM(
            CASE
              WHEN status IN (${activePlaceholders})
              THEN 1
              ELSE 0
            END
          ) AS in_progress,

          -- Count completed uploads.
          SUM(
            CASE
              WHEN status = 'completed'
              THEN 1
              ELSE 0
            END
          ) AS completed,

          -- Count failed uploads.
          SUM(
            CASE
              WHEN status = 'failed'
              THEN 1
              ELSE 0
            END
          ) AS failed

        FROM uploads
      `,
      )
      .get(...ACTIVE_UPLOAD_STATUSES);

    return {
      totalUploads: row.total_uploads,

      // SQLite SUM() may return null if there are no rows,
      // so use 0 instead.
      inProgress: row.in_progress ?? 0,
      completed: row.completed ?? 0,
      failed: row.failed ?? 0,
    };
  }

  // Update upload progress while the file
  // is being transferred to OpenSpace.
  function updateTransferProgress(id, patch) {
    // Make sure the upload exists.
    requireUpload(id);

    const now = new Date().toISOString();

    // Make sure fileSize is never 0.
    //
    // This prevents division-by-zero when
    // calculating upload percentage.
    const fileSize = Math.max(patch.fileSize || 0, 1);

    // Ensure bytesSent stays between:
    //
    // 0 <= bytesSent <= fileSize
    const bytesSent = Math.min(Math.max(patch.bytesSent || 0, 0), fileSize);

    // Calculate upload percentage.
    //
    // Example:
    // 500 / 1000 * 100 = 50%
    const progress = Math.min(100, Math.round((bytesSent / fileSize) * 100));

    database
      .prepare(
        `
        UPDATE uploads
        SET
          status = 'uploading',
          bytes_sent = ?,
          upload_progress = ?,

          -- Only set upload_started_at the first time.
          upload_started_at =
            COALESCE(upload_started_at, ?),

          updated_at = ?

        WHERE id = ?
      `,
      )
      .run(bytesSent, progress, now, now, id);

    return findById(id);
  }

  // Store the IDs returned by OpenSpace
  // after remote resources have been created.
  function setRemoteIds(id, captureId, uploadId) {
    requireUpload(id);

    database
      .prepare(
        `
        UPDATE uploads
        SET
          capture_id = ?,
          openspace_upload_id = ?,
          updated_at = ?
        WHERE id = ?
      `,
      )
      .run(captureId, uploadId, new Date().toISOString(), id);
  }

  // Mark the upload as submitted after
  // the complete file has been transferred.
  function markSubmitted(id, viewerUrl) {
    requireUpload(id);

    const now = new Date().toISOString();

    database
      .prepare(
        `
        UPDATE uploads
        SET
          status = 'submitted',

          -- Entire file has been sent.
          bytes_sent = file_size,
          upload_progress = 100,

          viewer_url = ?,
          submitted_at = ?,
          updated_at = ?

        WHERE id = ?
      `,
      )
      .run(viewerUrl ?? null, now, now, id);

    return findById(id);
  }

  // Mark the upload as being processed
  // by the remote OpenSpace service.
  function markProcessing(id) {
    requireUpload(id);

    database
      .prepare(
        `
        UPDATE uploads
        SET
          status = 'processing',
          updated_at = ?
        WHERE id = ?
      `,
      )
      .run(new Date().toISOString(), id);

    return findById(id);
  }

  // Mark an upload as successfully completed.
  function markCompleted(id) {
    requireUpload(id);

    const now = new Date().toISOString();

    database
      .prepare(
        `
        UPDATE uploads
        SET
          status = 'completed',

          -- Completed uploads always show 100%.
          upload_progress = 100,

          -- Clear any previous error.
          error_message = NULL,

          processing_completed_at = ?,
          updated_at = ?

        WHERE id = ?
      `,
      )
      .run(now, now, id);

    return findById(id);
  }

  // Mark an upload as failed and save
  // the related error message.
  function markFailed(id, errorMessage) {
    requireUpload(id);

    database
      .prepare(
        `
        UPDATE uploads
        SET
          status = 'failed',
          error_message = ?,
          updated_at = ?
        WHERE id = ?
      `,
      )
      .run(
        // Always store a readable error string.
        String(errorMessage || "Upload failed."),

        new Date().toISOString(),
        id,
      );

    return findById(id);
  }

  // Mark an upload as intentionally cancelled.
  function markCancelled(id) {
    requireUpload(id);

    database
      .prepare(
        `
        UPDATE uploads
        SET
          status = 'cancelled',

          -- Cancellation is not necessarily an error,
          // so remove any old error message.
          error_message = NULL,

          updated_at = ?

        WHERE id = ?
      `,
      )
      .run(new Date().toISOString(), id);

    return findById(id);
  }

  // Record that the local INSV file
  // has been deleted from the machine.
  function markLocalFileDeleted(id) {
    database
      .prepare(
        `
        UPDATE uploads
        SET
          local_file_path = NULL,
          local_file_deleted = 1,
          updated_at = ?
        WHERE id = ?
      `,
      )
      .run(new Date().toISOString(), id);
  }

  // Reset a failed or cancelled upload
  // so it can be attempted again.
  function prepareRetry(id) {
    // Retry requires access to the local file path.
    const upload = requireUpload(id, {
      includeLocalPath: true,
    });

    // Only failed or cancelled uploads can be retried.
    if (!["failed", "cancelled"].includes(upload.status)) {
      throw new Error("Only a failed or cancelled upload can be retried.");
    }

    // The original local INSV file must still exist
    // or there is nothing available to upload again.
    if (!upload.localFilePath) {
      throw new Error("The local INSV file is no longer available for retry.");
    }

    const now = new Date().toISOString();

    database
      .prepare(
        `
        UPDATE uploads
        SET
          -- Remove previous OpenSpace IDs because
          -- a new remote upload attempt will be created.
          capture_id = NULL,
          openspace_upload_id = NULL,

          -- Reset the upload back to its initial state.
          status = 'staged',
          upload_progress = 0,
          bytes_sent = 0,

          -- Keep track of how many retry attempts were made.
          retry_count = retry_count + 1,

          -- Clear old error/status information.
          error_message = NULL,
          submitted_at = NULL,
          processing_completed_at = NULL,

          updated_at = ?

        WHERE id = ?
      `,
      )
      .run(now, id);

    // Return the reset upload including its local path,
    // since the caller will likely need the file for retry.
    return findById(id, {
      includeLocalPath: true,
    });
  }

  // Find uploads that had already been submitted
  // or were still processing before the application restarted.
  //
  // This lets the system resume checking OpenSpace
  // instead of uploading the files again.
  function listForProcessingResume() {
    return database
      .prepare(
        `
        SELECT *
        FROM uploads
        WHERE status IN (
          'submitted',
          'processing'
        )
      `,
      )
      .all()
      .map(mapUpload);
  }

  // Expose the public repository functions
  // that other parts of the application can use.
  return {
    create,
    findById,
    getDashboardSummary,
    getRecent,
    list,
    listForProcessingResume,
    markCancelled,
    markCompleted,
    markFailed,
    markLocalFileDeleted,
    markProcessing,
    markSubmitted,
    prepareRetry,
    setRemoteIds,
    updateTransferProgress,
  };
}
